pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'your_dockerhub_username/progression-app'
        DOCKER_TAG = "${BUILD_NUMBER}" 
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }


        stage('Test') {
            steps {
                script {
                   docker.image('python:3.9-alpine').inside {
                       sh 'python -m unittest test_app.py'
                   }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    customImage = docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub-credentials') {
                        customImage.push()
                        customImage.push('latest') 
                    }
                }
            }
        }
        
        stage('Cleanup') {
            steps {
                sh "docker rmi ${DOCKER_IMAGE}:${DOCKER_TAG}"
                sh "docker rmi ${DOCKER_IMAGE}:latest"
            }
        }
    }
}